name: Run PowerShell Script

on:
  push:
    branches:
      - main
    paths:
      - 'CreateWinVM.ps1'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PowerShell
      uses: actions/setup-powershell@v2

    - name: Run PowerShell Script
      shell: pwsh
      run: ./CreateWinVM.ps1
