name: PowerShell Script CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run PowerShell script syntax check
      shell: pwsh
      run: |
        Get-ChildItem *.ps1 | ForEach-Object {
          Write-Host "Checking syntax for:" $_.Name
          $null = Get-Command $_.FullName -ErrorAction Stop
        }
